project:
  type: website
  output-dir: docs 

website:
  title: "Harry's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/HaejinYoon
      - icon: instagram
        href: https://www.instagram.com/haeppy_harry_/
      - icon: facebook
        href: https://www.facebook.com/HJY0718
format:
  html:
    theme:
      - Simplex
    css: styles.css



